version: 2.1


jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # Whatever you want to do
      - run: docker ps
      - run: "curl -sL https://raw.githubusercontent.com/soluble-ai/soluble-cli/master/linux-install.sh | sh" 
      - run: "soluble image-scan --image nginx --upload"
